from analisis import *

def test_leer_datos(file_path)
def test_aplicar_filtro_gaussiano(dato, sigma=5)
def test_calcular_aceleracion_vertical(ay, a)
def test_estimar_gravedad(tiempo, a_v)
def test_restar_gravedad(a_v, aceleracion_gravitatoria)
def test_recortar_datos(tiempo, a_vertical_real, a_v, a_v_filtrado)
def test_primitiva_numerica(variable, tiempo, y0=0)
def test_calcular_fuerza(a_v_recortado, masa)
def test_calcular_max_min(signal)
def test_identificar_cambio_brusco(signal, sampling_rate=250, umbral=0.25)
def test_calcular_cinematica(tiempo_recortado, a_v_real_recortada, a_v_real_filtrado_recortado, masa, fuerza, fuerza_filtrada)
def test_calcular_altura_salto(velocidad_maxima, aceleracion_gravitatoria)
def test_get_datos_analisis(fichero, masa)
def test_grafica_aceleracion(fichero, masa)
def test_grafica_fuerza(fichero, masa)
def test_grafica_velocidad(fichero, masa)
def test_grafica_potencia(fichero, masa)